project:
  type: manuscript
  render: 
    - "index.qmd"
    - "notebooks/figure1_replication.qmd"
    - "notebooks/figure2_replication.qmd"
    - "notebooks/anes_external_efficacy_index_chart.qmd"

manuscript:
  meca-bundle: false
  # resources: 
  #   - resources/anes_timeseries_2020_userguidecodebook_20220210.pdf
  notebooks:
    - notebook: notebooks/figure1_replication.qmd
      title: "Figure 1 Replication"
    - notebook: notebooks/figure2_replication.qmd
      title: "Figure 2 Replication"
    # - notebook: notebooks/anes_external_efficacy_index_chart.qmd
    #   title: "ANES External Efficacy Index Chart"
  code-links: repo

execute:
  freeze: auto
  echo: false

notebook-links: false
bibliography: references.bib
date: last-modified
date-format: "YYYY-MM-DD"
citation:
  container-title: Manuscript

functions: place

format:
  html:
    toc: true
    toc-depth: 3
    embed-resources: false
    mainfont: STIX Two Text
    mathfont: New Computer Modern Math
    monofont: Fira Code
    link-citations: true
    smooth-scroll: true
    link-external-newwindow: true
    notebook-links: global
    citations-hover: true
    footnotes-hover: false
    theme: 
      light: flatly
      dark: darkly
  
  typpo-typst:
    keep-typ: false
    fig-width: 4
    fig-asp: 0.618
    # uncomment to adjust these options
    two-column: false # default is `two-column: true` layout
    # paper: "us-letter",    
    mainfont: "STIX Two Text"
    # mathfont: "New Computer Modern Math"
    # monofont: "Fira Code"
    # fontsize: 11pt
    leading: 0.75em # spacing between lines
    # spacing: 1.2em # spacing between paragaphs
    first-line-indent: 1em
    all: false
    linkcolor: maroon
    # title-size: 1.5em,
    # subtitle-size: 1.25em,
    # sectionnumbering: "I.A.1",
    # pagenumbering: "1",
    # linenumbering: none
    # bibliography-title: "Reference"
    # bibliographystyle: "chicago-author-date"
      
  # docx:
  #   reference-doc: custom-reference.docx
  #   knitr: 
  #     opts_chunk: 
  #       dev: "ragg_png"
  #       dpi: 300
  #       out.width: "80%"

  # submittable-docx:
  #   keep-md: true
  #   knitr: 
  #     opts_chunk: 
  #       dev: "ragg_png"
  #       dpi: 300
  #       out.width: "80%"

  # jats: default
  
  # pdf:
  #   pdf-engine: xelatex
  #   documentclass: scrartcl
  #   keep-tex: false
  #   # mainfont: Palatino Linotype
  #   mainfont: TeX Gyre Pagella
  #   mathfont: TeX Gyre Pagella Math
  #   fontsize: 11pt
  #   indent: true # indented paragraphs (indent=true) vs space between paragraphs
  #   linestretch: 1.5
  #   number-sections: false
  #   citecolor: RoyalBlue
  #   cap-location: top
  #   fig-height: 4
  #   fig-width: 7.5
  #   link-citations: true
  #   papersize: a4
  #   hyperrefoptions: 
  #     - linktoc=all
  #     - pdfwindowui
  #     - pdfpagemode=FullScreen
  #   geometry:
  #     - inner=3cm
  #     - outer=4cm
  #     - top=3cm
  #     - bottom=4cm
  #     - headsep=22pt
  #     - headheight=11pt
  #     - footskip=33pt
  #     - ignorehead
  #     - ignorefoot
  #     - heightrounded



